[frontend]
frontend-ec2 ansible_host=10.0.1.50 ansible_user=ubuntu

[scout]
scout-ec2 ansible_host=10.0.10.20 ansible_user=ubuntu

[enricher]
enricher-ec2 ansible_host=10.0.11.30 ansible_user=ubuntu

[outreach]
outreach-ec2 ansible_host=10.0.10.40 ansible_user=ubuntu

[agents:children]
scout
enricher
outreach

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
GHCR_OWNER=joanr
IMAGE_TAG=latest
